theme: jekyll-theme-modernist
show_downloads: true
# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: Nano33 BLE Applied Emotion Classification for Motions of Musical Instruments 
description: Project for UCLA ECEM202A/CSM213A (Fall 2022)
